version: '3.8'
volumes:
  postgres_data:
  nginx_static:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: jeniusams/api_yamdb_web:v1
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx-yamdb:5
    restart: always
    volumes:
      - nginx_static:/data/www/static/
    ports:
      - "80:80"
    depends_on:
      - web
