version: '3.8'
volumes:
  postgres_data:
  nginx_static:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: jeniusams/yamdb_final:latest
    restart: always
    volumes:
      - nginx_static:/code/static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.7
    restart: always
    volumes:
      - nginx_static:/data/www/static/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
