version: '3.8'
volumes:
  postgres_data:
  yamdb_static:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: jeniusams/yamdb_final:latest
    restart: always
    volumes:
      - yamdb_static:/code/static/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.7
    restart: always
    volumes:
      - yamdb_static:/data/www/static/
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
