# Generated by Django 3.1.2 on 2020-10-29 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10, 'Рейтинг не может быть выше 10'), django.core.validators.MinValueValidator(1)], verbose_name='Рейтинг'),
        ),
    ]
