# Generated by Django 3.1.2 on 2020-10-29 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20201029_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10, 'Оценка не может превышать 10'), django.core.validators.MinValueValidator(1)], verbose_name='Оценка'),
        ),
    ]
