name: YamDB_workflow

on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt

    - name: Lint with flake8
      run: flake8 .

    - name: Test with pytest
      run: pytest


  deploy:
    runs-on: ubuntu-latest
    #needs: build_and_push_to_docker_hub

    steps:
    - uses: actions/checkout@v2
      env:
       SUPER_SECRET2: ${{ secrets.DB_ENGINE }}
       SUPER_SECRET3: ${{ secrets.DB_PORT }}
    - name: Run a multi-line script
      run: |
       echo "SUPER_SECRET2&&3:"
       echo "$SUPER_SECRET2"
       echo "$SUPER_SECRET3"
    - name: Run a multi-line script
      run: |
        pwd
    - uses: SpicyPizza/create-envfile@v1
      with:
        ENV_DB_ENGINE: ${{ secrets.ENV_DB_ENGINE}}
        file_name: .env
      env:
        SUPER_SECRET: ${{ secrets.SuperSecret }}
    - name: Run a multi-line script
      run: |
        echo "SUPER_SECRET:"
        echo "$SUPER_SECRET"
        export
        echo "cat env:"
        cat .env
        ls
        pwd
        tar -cvf deploy.tar .
        
      
    - name: executing copy files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        source: deploy.tar
        target: yamdb_final

    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd yamdb_final
          tar -xvf deploy.tar
          sudo docker-compose stop
          sudo docker-compose up -d
          

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:

    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} successfully deployed!
