name: YamDB_workflow

on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt

    - name: Lint with flake8
      run: flake8 .

    - name: Test with pytest
      run: pytest

  deploy:
    runs-on: ubuntu-latest
    #needs: build_and_push_to_docker_hub
    steps:
    
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      #cp -TR . ../build
      run: |
        mkdir ../build
        tar -cvf deploy.tar .
      
    - name: executing copy files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        source: deploy.tar
        target: app_yamdb_final

    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd app_yamdb_final
          tar -xvf deploy.tar
          ls -l
          #sudo pwd && ls -l
          #sudo ls -l
          #sudo cd app_yamdb_final && ls -l
          #sudo mv env .env
          #sudo docker-compose stop
          #sudo docker-compose up -d



  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:

    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} successfully deployed!
